version: '3.8'

services:
  # MongoDB y tu aplicación existente
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  app:
    build: .
    container_name: scraper_app
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
    stdin_open: true
    tty: true

  # Elasticsearch para indexar los eventos
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always

  # Kibana para visualización
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: always

volumes:
  mongo_data:
  esdata:

