version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  app:
    build: .
    container_name: scraper_app
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
    stdin_open: true
    tty: true

volumes:
  mongo_data:
